In [1]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris

In [2]:
# Wczytanie zbioru danych Iris
iris = load_iris()

# Dane wejściowe
X = iris.data

# Etykiety klas
y = iris.target

# Nazwy cech
feature_names = iris.feature_names

# Nazwy klas
target_names = iris.target_names

print("Podstawowe informacje o zbiorze Iris")
print("------------------------------------")

print("Liczba próbek:", X.shape[0])
print("Liczba cech:", X.shape[1])
print("Kształt X:", X.shape)
print("Kształt y:", y.shape)

print("\nNazwy cech:")
print(feature_names)

print("\nDostępne klasy:")
print(target_names)

print("\nPierwsze 5 próbek danych wejściowych:")
print(X[:5])

print("\nPierwsze 5 etykiet:")
print(y[:5])

Podstawowe informacje o zbiorze Iris
------------------------------------
Liczba próbek: 150
Liczba cech: 4
Kształt X: (150, 4)
Kształt y: (150,)

Nazwy cech:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Dostępne klasy:
['setosa' 'versicolor' 'virginica']

Pierwsze 5 próbek danych wejściowych:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Pierwsze 5 etykiet:
[0 0 0 0 0]


In [3]:
# Zamiana danych na DataFrame

df = pd.DataFrame(X, columns=feature_names)

# Dodanie kolumny z etykietą liczbową
df["target"] = y

# Dodanie kolumny z nazwą gatunku
df["species"] = df["target"].map({
    0: target_names[0],
    1: target_names[1],
    2: target_names[2]
})

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa


In [4]:
# Informacje o danych

print("Informacje o DataFrame:")
print(df.info())

print("\nPodstawowe statystyki:")
print(df.describe())

print("\nLiczba przykładów w każdej klasie:")
print(df["species"].value_counts())

Informacje o DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
 5   species            150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None

Podstawowe statystyki:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%    