In [13]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# Część 3. Budowa modelu sieci neuronowej

import tensorflow as tf

I0000 00:00:1780487998.557237     231 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# Wczytanie zbioru danych Iris
iris = load_iris()

# Dane wejściowe
X = iris.data

# Etykiety klas
y = iris.target

# Nazwy cech
feature_names = iris.feature_names

# Nazwy klas
target_names = iris.target_names

print("Podstawowe informacje o zbiorze Iris")
print("------------------------------------")

print("Liczba próbek:", X.shape[0])
print("Liczba cech:", X.shape[1])
print("Kształt X:", X.shape)
print("Kształt y:", y.shape)

print("\nNazwy cech:")
print(feature_names)

print("\nDostępne klasy:")
print(target_names)

print("\nPierwsze 5 próbek danych wejściowych:")
print(X[:5])

print("\nPierwsze 5 etykiet:")
print(y[:5])

Podstawowe informacje o zbiorze Iris
------------------------------------
Liczba próbek: 150
Liczba cech: 4
Kształt X: (150, 4)
Kształt y: (150,)

Nazwy cech:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Dostępne klasy:
['setosa' 'versicolor' 'virginica']

Pierwsze 5 próbek danych wejściowych:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Pierwsze 5 etykiet:
[0 0 0 0 0]


In [3]:
# Zamiana danych na DataFrame

df = pd.DataFrame(X, columns=feature_names)

# Dodanie kolumny z etykietą liczbową
df["target"] = y

# Dodanie kolumny z nazwą gatunku
df["species"] = df["target"].map({
    0: target_names[0],
    1: target_names[1],
    2: target_names[2]
})

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa


In [4]:
# Informacje o danych

print("Informacje o DataFrame:")
print(df.info())

print("\nPodstawowe statystyki:")
print(df.describe())

print("\nLiczba przykładów w każdej klasie:")
print(df["species"].value_counts())

Informacje o DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
 5   species            150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None

Podstawowe statystyki:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%    

In [6]:
# Podział danych na zbiór treningowy i testowy
# test_size=0.2 oznacza, że 20% danych trafi do zbioru testowego
# random_state zapewnia powtarzalność wyniku
# stratify=y pilnuje, aby proporcje klas były podobne w zbiorze treningowym i testowym

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [7]:
print("Rozmiary zbiorów po podziale")
print("----------------------------")

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

Rozmiary zbiorów po podziale
----------------------------
X_train shape: (120, 4)
X_test shape: (30, 4)
y_train shape: (120,)
y_test shape: (30,)


In [8]:
print("Rozkład klas w zbiorze treningowym:")
print(pd.Series(y_train).value_counts().sort_index())

print("\nRozkład klas w zbiorze testowym:")
print(pd.Series(y_test).value_counts().sort_index())

Rozkład klas w zbiorze treningowym:
0    40
1    40
2    40
Name: count, dtype: int64

Rozkład klas w zbiorze testowym:
0    10
1    10
2    10
Name: count, dtype: int64


In [9]:
# Utworzenie obiektu skalującego

scaler = StandardScaler()

In [10]:
# Dopasowanie scalera do danych treningowych i transformacja X_train

X_train_scaled = scaler.fit_transform(X_train)

# Transformacja danych testowych tym samym scalerem

X_test_scaled = scaler.transform(X_test)

In [11]:
print("Pierwsze 5 próbek przed standaryzacją:")
print(X_train[:5])

print("\nPierwsze 5 próbek po standaryzacji:")
print(X_train_scaled[:5])

Pierwsze 5 próbek przed standaryzacją:
[[4.4 2.9 1.4 0.2]
 [4.9 2.5 4.5 1.7]
 [6.8 2.8 4.8 1.4]
 [4.9 3.1 1.5 0.1]
 [5.5 2.5 4.  1.3]]

Pierwsze 5 próbek po standaryzacji:
[[-1.72156775 -0.33210111 -1.34572231 -1.32327558]
 [-1.12449223 -1.22765467  0.41450518  0.6517626 ]
 [ 1.14439475 -0.5559895   0.58484978  0.25675496]
 [-1.12449223  0.11567567 -1.28894078 -1.45494479]
 [-0.40800161 -1.22765467  0.13059752  0.12508575]]


In [12]:
print("Średnie cech po standaryzacji:")
print(X_train_scaled.mean(axis=0))

print("\nOdchylenia standardowe cech po standaryzacji:")
print(X_train_scaled.std(axis=0))

Średnie cech po standaryzacji:
[-1.20829273e-15 -2.03679666e-15  4.99600361e-16  1.67458640e-15]

Odchylenia standardowe cech po standaryzacji:
[1. 1. 1. 1.]


In [14]:
model = tf.keras.models.Sequential([
    # Warstwa wejściowa
    # Zbiór Iris ma 4 cechy wejściowe:
    # sepal length, sepal width, petal length, petal width
    tf.keras.layers.Input(shape=(4,)),

    # Pierwsza warstwa ukryta
    tf.keras.layers.Dense(
        16,
        activation="relu"
    ),

    # Druga warstwa ukryta
    tf.keras.layers.Dense(
        8,
        activation="relu"
    ),

    # Warstwa wyjściowa
    # Mamy 3 klasy: setosa, versicolor, virginica
    tf.keras.layers.Dense(
        3,
        activation="softmax"
    )
])

In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type) ┃ Output Shape ┃ Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense ( Dense ) │ ( None , 16 ) │ 80 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 ( Dense ) │ ( None , 8 ) │ 136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 ( Dense ) │ ( None , 3 ) │ 27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

Total params: 243 (972.00 B)

Trainable params: 243 (972.00 B)

Non-trainable params: 0 (0.00 B)

In [16]:
# ============================================================
# Część 4. Kompilacja modelu
# ============================================================

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)


# ============================================================
# Część 5. Trenowanie modelu
# ============================================================

history = model.fit(
    X_train_scaled,
    y_train,
    epochs=50,
    batch_size=8,
    validation_split=0.2,
    verbose=1
)


# ============================================================
# Część 6. Ocena modelu
# ============================================================

test_loss, test_accuracy = model.evaluate(
    X_test_scaled,
    y_test,
    verbose=0
)

print("\nWyniki na zbiorze testowym")
print("--------------------------")
print(f"Test loss: {test_loss:.4f}")
print(f"Test accuracy: {test_accuracy:.4f}")


# ============================================================
# Krótka interpretacja wyniku
# ============================================================

print("\nInterpretacja")
print("-------------")

if test_accuracy >= 0.95:
    print("Model osiągnął bardzo wysoką dokładność.")
elif test_accuracy >= 0.85:
    print("Model osiągnął dobrą dokładność.")
else:
    print("Model wymaga poprawy.")

random_accuracy = 1 / 3

print("\nPorównanie z losowym zgadywaniem:")
print(f"Losowe zgadywanie dla 3 klas: {random_accuracy:.4f}")
print(f"Dokładność modelu: {test_accuracy:.4f}")

if test_accuracy > random_accuracy:
    print("Model działa lepiej niż losowe zgadywanie.")
else:
    print("Model nie działa lepiej niż losowe zgadywanie.")

Epoch 1/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.3646 - loss: 1.3791 - val_accuracy: 0.3333 - val_loss: 1.4584
Epoch 2/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3646 - loss: 1.2643 - val_accuracy: 0.2917 - val_loss: 1.3502
Epoch 3/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3646 - loss: 1.1814 - val_accuracy: 0.3333 - val_loss: 1.2534
Epoch 4/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4062 - loss: 1.0960 - val_accuracy: 0.2917 - val_loss: 1.1712
Epoch 5/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4479 - loss: 1.0218 - val_accuracy: 0.3750 - val_loss: 1.1037
Epoch 6/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5104 - loss: 0.9568 - val_accuracy: 0.4167 - val_loss: 1.0399
Epoch 7/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6042 - loss: 0.9018 - val_accuracy: 0.5417 - val_loss: 0.9816
Epoch 8/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6875 - loss: 0.8469 - val_accuracy: 0.6250 - val_los